# Generated by Django 5.1.2 on 2024-10-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('college_logo', models.ImageField(upload_to='logos/')),
                ('instructions', models.TextField()),
                ('college_profile', models.TextField()),
            ],
        ),
    ]
